export default {
  SHOW_MOVIE_DETAILS: 'SHOW_MOVIE_DETAILS',
  HIDE_MOVIE_DETAILS: 'HIDE_MOVIE_DETAILS',
  SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
  SEARCH_MOVIES_START: 'SEARCH_MOVIES_START',
};
